- rhtap/cosign-sign-attest.sh
I had it backwards and my local cosign was unexpectedly old.
This reverts commit 9fa0561632323d73e4b54d1bee8f9826dd908de6.
> Revert "Fix old cosign param used to skip rekor upload"

- .gitlab-ci.yml
- Dockerfile.gitlab
- Makefile
- rhtap/buildah-rhtap.sh
- templates/.gitlab-ci.yml.njk
- Create a runner image that contains the bash scripts and required dependencies
- Use that base image in the GitLab pipeline
- Convert the GitLab pipeline to a template and make it more similar to the others
- Change how the docker credential is provided for cosign (see commit message for more detail)
Ref: [EC-928](https://issues.redhat.com/browse/EC-928)
> New GitLab pipeline using common base image

- .github/workflows/build-and-update-gitops.yml
- Dockerfile.github
- build-pipeline.sh
- ci-test.sh
- copy-scripts.sh
- dev-build.dockerfile
- hack/copy-to-tssc-templates
- hack/ghub-set-vars
- promote-pipeline.sh
- rhtap/acs-deploy-check.sh
- rhtap/common.sh
- setup-local-dev-repos.sh
- templates/build-and-update-gitops.yml.njk
PR contains changes to allow a ci-test.sh script to copy into the users repo and test the CI.
- test Jenkins, gitlab and github CI from current repo (uncommitted)
- updated images for gitlab and github
- update tasks to allow disable gitops updates
- auto-set secrets for use repos for testing
- Uses MY_QUAY_USER for images and MY_GITHUB_USER for git repo
- removal of personal github accounts
> ci test script

- rhtap/download-sbom-from-url-in-attestation.sh
This is the first big piece of the "upload SBOMs to TPA" functionality. It downloads the thing that another script will then upload :)
Usage:
```bash
IMAGE=quay.io/...
IMAGES=$(jq --arg image "$IMAGE" -n -c '{"components": [{"containerImage": $image}]}') IGNORE_REKOR=true REKOR_HOST='' TUF_MIRROR='' PUBLIC_KEY=tmp/build/results/cosign-sign-attest/cosign.pub rhtap/download-sbom-from-url-in-attestation.sh
tree .sboms
```
I haven't managed to integrate it into the promotion pipeline yet
> Add download-sbom-from-url-in-attestation.sh

- rhtap/update-deployment.sh
Note: The same code is in tasks/json/update-deployment.json but I'm not sure if that is dead code or if it is updated automatically, so I'm leaving it alone in this commit.
The second commit adjusts the "noreply" email address.
> Don't use git config --global to set commit author

- Dockerfile.github
- Dockerfile.gitlab
- rhtap/att-predicate-github.sh
- rhtap/att-predicate-gitlab.sh
- rhtap/att-predicate-jenkins.sh
- rhtap/cosign-sign-attest.sh
Use the CI_TYPE var to decide which one to use.
Filling in more useful content is still to do, but I want to merge this early to solidify the selection mechanism, and confirm things are working as expected.
Ref: [EC-987](https://issues.redhat.com/browse/EC-987)
> Add attestation predicates for GitLab and GitHub

- .gitignore
Used by direnv[1] to set per directory environment variables.
[1] https://github.com/direnv/direnv
> Ignore `.envrc` file

- rhtap/cosign-sign-attest.sh
Makes it tiny bit more readable.
> Use recognized type in `cosign attest`

- hack/copy-to-tssc-templates
- Eventually we should change where files are generated , so we can simplify these scripts. I would prefer a destination per ci something like   
> generated/ciType/source and generated/ciType/gitops
- removes the needs for renames and sed hacking of the files and also does not leave generated files in locations that are "live" like .github or Jenkinsfile
> updates to simplify release  scripts

- rhtap/att-predicate-github.sh
Adds fields akin to what what actions/attest-build-provenance[1] would generate.
Reference: https://issues.redhat.com/browse/EC-989
[1] https://github.com/actions/attest-build-provenance
> GitHub workflow attestation refinement

- .github/workflows/checks.yml
Just run the existing make target.
Ref: https://issues.redhat.com/browse/RHTAP-3261
> Add CI to ensure generated files are fresh

- rhtap.groovy
- templates/rhtap.groovy.njk
cosign-sign-attest.sh now depends on att-predicate-jenkins.sh, but the latter wasn't getting installed.
> Jenkins: install missing script

- ci-test.sh
- hack/copy-to-tssc-templates
Update the copy scripts to reference the generated templates directory.
- copy-to-tssc-templates.sh copys the directory and contents so if/when we add techdocs it will update automatically
- ci-test only copies the specific CI files to avoid overwriting ther files in the test repos
> update scripts for generated files

- Makefile
- generated/gitops-template/githubactions/.github/workflows/gitops-promotion.yml
- generated/gitops-template/gitlabci/.gitlab-ci.yml
- generated/gitops-template/jenkins/Jenkinsfile
- rhtap.groovy
- rhtap/gather-deploy-images.sh
- rhtap/gather-images-to-upload-sbom.sh
- rhtap/promote-pipeline-steps.sh
- templates/data.yaml
This is a hacky way to integrate the SBOM-downloading into the promotion pipeline
* We need to call the gather-images script twice with different params. Work around that by adding another script that calls it with the params we need.
* The second run of gather-images will just overwrite the results of the first one. This is fine at the moment, because the entire pipeline runs serially (I think?). It would still be possible to run the two `gitops_steps` in parallel if they each ran in a separate environment.
> Download SBOM in promotion pipeline

- hack/jenkins-create-secret
- hack/jenkins-create-user-password
Previously, the secrets were getting created with extra whitespace. Somehow this worked fine in *most* cases but not always. For example, the 'deploy' step in a build pipeline would fail with
Failed to push update to gitops repository: https://github.com/acmiel-rhtap/rhtap-python-gitops
Do you have correct git credentials configured?
After removing the extra whitespace, the step started working.
> Jenkins: fix extra whitespace in secrets

- ci-test.sh
- init-tas-vars.sh
This pr updates the ci-test script to compute the rekor and tuf endpoint.
ci-test can be used to test all three (jenkins, github actions and gitlab) with the same script.
TODO - ci-test currently requires you update the gitlab and github runner image prior and and jenkins repo manually. Then you run ci-test and it updates the forks with new pipeline content. It was done this way to allow testing ci by runing this once and just updating the jenkins lib and / or images but can be error prone if you forget.
> Comput rekor-tufs endpoints in-test script

- rhtap.groovy
- templates/rhtap.groovy.njk
The gather-images-to-upload-sbom.sh script depends on gather-deploy-images.sh, but the latter wasn't getting installed explicitly.
The pipeline does work, because the gather-deploy-images.sh script coincidentally gets installed by an earlier step in the pipeline. But make sure to install it explicitly to avoid future problems.
> Jenkins: install another missing script

- templates/data.yaml
- templates/gitops-template/.gitlab-ci.yml.njk
- templates/source-repo/.gitlab-ci.yml.njk
In some cases we need to ensure tasks run sequentially, but setting the "concurrent" field lets them run in parallel like they do now.
Note that currently GitLab is the only CI type that runs the steps in parallel when "concurrent" is set. Making Jenkins and GitHub behave that way too is something for the future.
> Run steps sequentially in GitLab by default

- generated/source-repo/githubactions/.github/workflows/build-and-update-gitops.yml
- templates/source-repo/build-and-update-gitops.yml.njk
The main issue with running a container on GitHub Actions seems to be with the default AppArmor profile configured -- it does not allow user namespaces needed by buildah.
Another characteristic of GitHub Actions is that the container configured for a Workflow job is used for all steps, so we can't run a command on the host to enable user namespaces. So running something like:
sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0
is not possible.
This resorts to running the container with extended privileges in order to allow user namespaces.
Resolves: https://issues.redhat.com/browse/RHTAP-3066
Followup to #16
> Use runner image for GitHub

- generated/source-repo/githubactions/.github/workflows/build-and-update-gitops.yml
- templates/source-repo/build-and-update-gitops.yml.njk
Need to figure out how to avoid these errors:
fatal: detected dubious ownership in repository at '/__w/rhtap-ci-tester/rhtap-ci-tester'
To add an exception for this directory, call:
git config --global --add safe.directory /__w/rhtap-ci-tester/rhtap-ci-tester
This reverts commit 7697a6d73d143bd18b84886470fddc356814aab5.
> Revert "Use runner image for GitHub"

- Dockerfile
- Makefile
- copy-scripts.sh
- generated/gitops-template/githubactions/.github/workflows/gitops-promotion.yml
- generated/gitops-template/gitlabci/.gitlab-ci.yml
- generated/source-repo/githubactions/.github/workflows/build-and-update-gitops.yml
- generated/source-repo/gitlabci/.gitlab-ci.yml
- templates/gitops-template/.gitlab-ci.yml.njk
- templates/gitops-template/gitops-promotion.yml.njk
- templates/source-repo/.gitlab-ci.yml.njk
- templates/source-repo/build-and-update-gitops.yml.njk
In #58 we changed the GitHub build pipeline to use the docker runner image. This PR changes the promote pipeline similarly.
There are some additional cleanups and tweaks, see commits for details.
Ref: https://issues.redhat.com/browse/RHTAP-3066
> Use runner image for GitHub promote pipeline also

- Dockerfile
Update ec and the syft binaries. The cosign and yq binaries don't need an update.
> Update two dependencies in the task runner image

- rhtap/acs-deploy-check.sh
Update deployment also needs access to the gitops repo so process auth before cloning
> add login to handle private repos

- ci-test.sh
- hack/jenkins-create-secret
- setup-local-dev-repos.sh
Fix jenkins in testing using ci-test.sh
1. use a separate repos for src,gitops so that the update-deployment does not overlap it with github actions
2. fix jenkins set secrets to allow replace values by deleting and then replacing
> update ci-tests to use a  separate jenkins-repos

- rhtap/download-sbom-from-url-in-attestation.sh
Currently, when there are no SBOMs to download->upload, the pipeline fails because the upload-sbom script runs on a non-existing directory.
Even if there are no SBOMs to download, create an empty SBOMS_DIR. This should serve as an indication for the upload-sbom script that everything ran correctly, but there really are no SBOMs to upload.
> download-sbom: always create SBOMS_DIR

- Dockerfile
Pulling from `docker.io` will not be acceptable for releasing via the Red Hat instance of Konflux
Also pin to digest
> Fix the runner-image base image

- generated/gitops-template/githubactions/.github/workflows/gitops-promotion.yml
- generated/source-repo/githubactions/.github/workflows/build-and-update-gitops.yml
- render/render.cjs
- templates/data.yaml
- templates/gitops-template/gitops-promotion.yml.njk
- templates/partials/jenkins-secret.njk
- templates/source-repo/build-and-update-gitops.yml.njk
Adresses the TODOs in the workflow files about using the secrets list from templates/data.yaml
> Fix the templating of secret variables in github pipelines

- generated/gitops-template/githubactions/.github/workflows/gitops-promotion.yml
- hack/ghub-set-vars
- rhtap/upload-sbom-to-trustification.sh
- templates/gitops-template/gitops-promotion.yml.njk
- remove comments from githubscripts (they break the scripts) - prior PR added them
- Special Hack: Allow blanks in GHUB secrets for TRUSTIFICATION which enable the CLI to set without prompting the user
> fix github secrets validation

- hack/wait-for-gitops-update.sh
- rhtap/acs-deploy-check.sh
- rhtap/buildah-rhtap.sh
- rhtap/cosign-sign-attest.sh
- rhtap/update-deployment.sh
The credentials code to create .git-credentials had errors. This PR fixes those to enable private gitops repos
In testing, I noticed the utility I use to automatically do pull-requests was taking too long due to the "raw" urls being cached --- converted to use repos directly and added to this PR
> Credentials fix for private repos

- hack/ghub-set-vars
- hack/glab-get-vars
- hack/glab-set-vars
- setup-local-dev-repos.sh
I've put three mostly unrelated ci-test.sh improvements in this one PR:
- Support using `git@github.com:$org/$repo.git` remotes for local test repos. This makes it easier to use ssh key based auth.
- Skip the extra git clone before using `gh secret set`. Instead use the `--repo` command line option.
- Always clone from the "upstream" sample repo, and do a force push to the "fork" sample repo.
Ref: https://issues.redhat.com/browse/RHTAP-3322
> Three ci-test improvements

- generated/gitops-template/githubactions/.github/workflows/gitops-promotion.yml
- generated/gitops-template/jenkins/Jenkinsfile
- generated/source-repo/githubactions/.github/workflows/build-and-update-gitops.yml
- generated/source-repo/jenkins/Jenkinsfile
- templates/data.yaml
REKOR_HOST and TUF_MIRROR are not exposed and can't be set by users in secrets/credentials in GH Actions and Jenkins
Expose them in GH Actions.
When getting an environment variable from secrets, GitHub always creates an env var, it just sets it to an empty string when secret is not set. This is going to be handled in env.sh in template definitions
Add them to Jenkins too, but leave them commented out and let users uncomment them when needed
Related https://github.com/redhat-appstudio/tssc-sample-templates/pull/106
> expose REKOR and TUF in GH Actions and Jenkins

- ci-test.sh
New option to not replace upstream names with user built component. 
Useful for testing exact images and branches at release time
Setting this will keep the redhat-appstudio images and jenkins repos instead of using the ones in the users space.
> USE_RHTAP_IMAGES flag

- rhtap/download-sbom-from-url-in-attestation.sh
The init.sh file is not run as part of the gitops pipeline so the SBOM dir was not being reset.    
This can result in multiple sboms being uploaded if you are using a long running Jenkins.
> ensure sbom dir is empty

- hack/rhtap-promote
Clean up the generation of a PR script on Github. 
Old way set the default for gh which is not required if you pass the repo with -R.
Now it works for your org repos (useful for RHDH/RHTAP Templates) and your personal repos.
> Update promote script

- generated/gitops-template/githubactions/.github/workflows/gitops-promotion.yml
- generated/source-repo/githubactions/.github/workflows/build-and-update-gitops.yml
- templates/gitops-template/gitops-promotion.yml.njk
- templates/source-repo/build-and-update-gitops.yml.njk
GitHub has announced that ubuntu-20.04 will no longer be supported starting on April 1st, 2025. This commit removes the comment about using that image as an option in order to avoid confusion.
> Remove note about ubuntu-20.04

- Dockerfile
- rhtap/verify-enterprise-contract.sh
This is required for displaying a human readable version of the EC report from the logs in the UI.
Ref: RHTAP-4019
Also added a change to reduce the context of the runner image build by only copying the `tools` directory in the Dockerfile.
> Add eyecatchers for the EC report

- .tekton/rhtap-task-runner-pull-request.yaml
- .tekton/rhtap-task-runner-push.yaml
rhtap-task-runner PipelineRuns currently run on every PR and every push 
Only changes that should affect rhtap-task-runner should be:
- change to PipelineRun definition itself
- change to the Dockerfile
- change to the tools directory which is copied in Dockerfile
> Run rhtap-task-runner PipelineRuns only when needed

- README.md
- generated/source-repo/githubactions/.github/workflows/build-and-update-gitops.yml
- generated/source-repo/gitlabci/.gitlab-ci.yml
- generated/source-repo/jenkins/Jenkinsfile
- rhtap.groovy
- rhtap/build-pipeline-steps.sh
- templates/data.yaml
'acs-deploy-check' checks out the gitops repository to validate the deployment, but that repository was updated after the check.
> fix: run update-deployment before acs-deploy-check

- .gitignore
.idea directory is used for storing settings of the IntelliJ-family of IDEs. It should not be included in the repository.
> Add .idea directory to gitignore

- rhtap/att-predicate-azure.sh
- rhtap/att-predicate-jenkins.sh
Update the SLSA Provenance generation code to always use the `.runDetails.metadata.invocationId` attribute. In some cases, Azure and Jenkins, `invocationId` was written as `invocationID` (upper case `D`).
This follows the SLSA Provenance 1.0 spec:
https://slsa.dev/spec/v1.0/provenance#buildmetadata
> Use consistent invocationId attribute

- rhtap/buildah-rhtap.sh
In https://github.com/redhat-appstudio/tssc-dev-multi-ci/pull/158, the login cosolidation didn't take into account the buildah-rhtap script. This caused the `cosign` command running within that script to fail to upload SBOMs.
Ref: https://issues.redhat.com/browse/RHTAP-4565
> Fix login consolidation for buildah-rhtap

- Makefile
- ci-test.sh
This PR is composed of several standalone minor changes to `ci-test.sh`.
They are aiming to improve the user experience when using non-Linux systems (macOS in my particular case) and improve readability and extensibility allowing to add support for new CI providers more easily.
Notes for reviewers:
- If possible, please try to run `bash ci-test.sh` if you're using a Linux system to double-check that the compatibility changes for macOS do not affect Linux systems
- The PR is split into several standalone commits with descriptions. I would recommend reviewing them one by one
> Compatibility improvements and cleanup of ci-test.sh

- Makefile
- generated/source-repo/azure/azure-pipelines.yml
- templates/data.yaml
- templates/partials/azure-step.njk
- templates/source-repo/azure-pipelines.yml.njk
Based on https://github.com/redhat-appstudio/tssc-dev-multi-ci/pull/137 which should be merged first. 
Review the last commit that adds the Azure source-repo pipeline
> Add Azure source-repo pipeline

- tools/syft/go.mod
- tools/yq/go.mod
Update the version of specified in the go.mod files for yq and syft to reflect the go version used in the builder image from the Dockerfile.
The previous version had CVEs so this ensures those binaries are not built (in other contexts) with a vulnerable version of Go.
> Update go.mod version to reflect builder image

- hack/wait-for-gitops-update.sh
- rhtap/gather-deploy-images.sh
This is needed to ensure the bootstrap image is not unexpectedly
validated by EC/Conforma which would fail since that image is not build
as part of the user's application.
Also change the check from an exact match to a prefix check instead.
This allows for the various version tags of the task-runner-image.
Ref: https://issues.redhat.com/browse/RHTAP-5219
> Add the new bootstrap image to default list

- hack/wait-for-gitops-update.sh
- rhtap/gather-deploy-images.sh
Add the runner image that is built and released from the main branch to the list of default init images. This allows us to perform pre-release tests more accurately.
> Add runner image from main to default list

- generated/gitops-template/azure/azure-pipelines.yml
- generated/source-repo/azure/azure-pipelines.yml
- templates/gitops-template/azure-pipelines.yml.njk
- templates/source-repo/azure-pipelines.yml.njk
By default, if an Azure pipeline does not define a `pr` attribute, Azure takes the default behavior of running the pipeline for *every* pull request.
Similarly, if the `trigger` attribute is not defined, the pipeline runs for push commits on *every* branch in the repo.
It is possible to change this default behavior on the Azure side: https://learn.microsoft.com/en-us/azure/devops/release-notes/2023/sprint-227-update#prevent-unintended-pipeline-runs
However, since these pipelines are only ever meant to be executed on specific events, we can change the default behavior by setting the `pr` and the `trigger` attributes to `none` where they weren't previously defined.
Ref: https://issues.redhat.com/browse/RHTAP-5246
> Prevent unintended Azure pipeline runs

- rhtap/acs-image-check.sh
cf RHTAP-5243
rh-pre-commit.version: 2.3.2
rh-pre-commit.check-secrets: ENABLED
> fix: improve acs-image-check output

- Dockerfile
As part of RHTAP-5277, we want to start using the runner image in the Tekton Tasks. The verify-ec Task uses the reduce-snapshot.sh script in one of its steps. This commit adds the script from the official EC image to the runner image.
> Add reduce-snapshot.sh script to runner image

- Dockerfile
As part of RHTAP-5275, we want to start using the runner image in the Tekton Tasks. A few Tasks use the oc binary for various operations. This commit adds the latest released oc binary to the runner image.
> Include the oc binary in runner image

- README.md
- generated/gitops-template/azure/azure-pipelines.yml
- generated/gitops-template/githubactions/.github/workflows/gitops-promotion.yml
- generated/gitops-template/gitlabci/.gitlab-ci.yml
- generated/gitops-template/jenkins/Jenkinsfile
- generated/source-repo/azure/azure-pipelines.yml
- generated/source-repo/githubactions/.github/workflows/build-and-update-gitops.yml
- generated/source-repo/gitlabci/.gitlab-ci.yml
- generated/source-repo/jenkins/Jenkinsfile
- hack/wait-for-gitops-update.sh
- rhtap/gather-deploy-images.sh
- templates/gitops-template/.gitlab-ci.yml.njk
- templates/gitops-template/azure-pipelines.yml.njk
- templates/gitops-template/gitops-promotion.yml.njk
- templates/partials/jenkins-library-source.njk
- templates/source-repo/.gitlab-ci.yml.njk
- templates/source-repo/azure-pipelines.yml.njk
- templates/source-repo/build-and-update-gitops.yml.njk
Change to multi-ci for 1.7 release
> Releasing 1.7

- rhtap/upload-sbom-to-trustification.sh
In some cases, 'transfer-encoding: chunked' is causing curl to hang indefinetly when uploading an SBOM. There are two reasons one may want to use this chunked encoding.
First, if the length of the content being uploaded is unknown. This is not the case here since we have the full file before making the API call.
Second, if the file being uploaded is excessively large, the targeted server may require the data to be streamed via chunks. Although SBOMs can be quite large, we don't seem to be anywhere near it. (The limit on TPA is currently not documented.)
It is also important to call out that when using chunked encoding, "the content-length header must be omitted":
https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Headers/Transfer-Encoding#chunked
For these reasonse, this commit …
> Remove chunked encoding

- rhtap/acs-image-check.sh
If there are no main issues found with the roxctl command, it exits with a 0 return code. Previously, the `acs-image-check` script would just do exit early if that happened. This caused the eyecatcher report to be omitted. This commit fixes that by returning from that function instead of exiting the script completely.
> acs-image-check: emit report on success
