- .gitignore
- Jenkinsfile
- Jenkinsfile-local-shell-scripts
- Jenkinsfile.gitops
- Jenkinsfile.gitops-local-shell
- Makefile
- render/package-lock.json
- render/package.json
- render/render.cjs
- templates/Jenkinsfile-local-shell-scripts.njk
- templates/Jenkinsfile.gitops-local-shell.njk
- templates/Jenkinsfile.gitops.njk
- templates/Jenkinsfile.njk
- templates/data.yaml
- templates/partials/do-not-edit.njk
- templates/partials/jenkins-library-source.njk
- templates/partials/jenkins-secret.njk
- templates/partials/jenkins-step-local.njk
- templates/partials/jenkins-step.njk
This was originally prototyped in [simonbaird/rhtap-ci-builder](https://github.com/simonbaird/rhtap-ci-builder). Now I'm bringing it in to this repo.
In this PR only the Jenkins files are becoming template managed. The other pipelines will be added in a future PR.
Ref: [EC-915](https://issues.redhat.com/browse/EC-915)
> Introduce Nunjucks templating

- Jenkinsfile
- Jenkinsfile-local-shell-scripts
- Makefile
- templates/build-and-update-gitops.yml.njk
- templates/data.yaml
(See commit messages for explanations.)
Ref: [EC-915](https://issues.redhat.com/browse/EC-915)
> Template the GitHub pipeline also

- Makefile
- hack/copy-to-tssc-templates
- render/render.cjs
- rhtap.groovy
- templates/rhtap.groovy.njk
This file is used in the
https://github.com/redhat-appstudio/tssc-sample-jenkins/ repo.
Let's generate it rather than maintain it by hand.
Ref: [EC-915](https://issues.redhat.com/browse/EC-915)
> Generate an rhtap.groovy file using a template

- build-pipeline.sh
- promote-pipeline.sh
I don't have an ACS environment set up, so this gives me a nice way to skip those steps while I'm hacking.
> Use env vars to skip steps in local dev

- .gitlab-ci.gitops.yml
- .gitlab-ci.yml
- Dockerfile.github
- Makefile
- templates/.gitlab-ci.gitops.yml.njk
- templates/.gitlab-ci.yml.njk
I'm not 100% confident about the way I've set up the rules field, and how/when the workflows are going to be triggered, but let's start with this and see if it behaves the way we want it to.
Also includes some additional minor changes. See commits for details.
> Introduce gitops pipeline for GitLab

- hack/copy-to-tssc-templates
- rhtap/att-predicate-github.sh
- rhtap/att-predicate-gitlab.sh
- rhtap/att-predicate-jenkins.sh
- rhtap/cosign-sign-attest.sh
* cosign-sign-attest was not creating attestations
* copy-to-tssc-templates broken on my machine
* (as I found out later, it's also broken because of https://github.com/redhat-appstudio/tssc-dev-multi-ci/pull/34, but as I understand @jduimovich is working on that?)
> Miscellaneous fixes

- ci-test.sh
- hack/copy-to-tssc-templates
I merged #40 with failing CI. This should get it green again.
> Minor bash script formatting fixes

- generated/gitops-template/gitlabci/.gitlab-ci.yml
- templates/gitops-template/.gitlab-ci.yml.njk
- templates/source-repo/.gitlab-ci.yml.njk
By default GitLab tries to run them in parallel.
> Ensure GitLab GitOps pipeline steps run sequentially

- rhtap/att-predicate-gitlab.sh
Tried to make this similar to the GitHub one, perhaps there is more common ground that can be found here.
Resolves: https://issues.redhat.com/browse/EC-988
> Refine GitLab attestation

- rhtap/env.template.sh
I just merged https://github.com/enterprise-contract/config/pull/149 so the two new configs are now available.
Ref: https://issues.redhat.com/browse/EC-990
Ref: https://issues.redhat.com/browse/EC-991
> Use specific config for EC based on CI_TYPE

- generated/source-repo/githubactions/.github/workflows/build-and-update-gitops.yml
- templates/source-repo/build-and-update-gitops.yml.njk
#53 was reverted in #57. This PR brings it back with one extra fix.
> Bring back the GitHub runner for the build pipeline

- hack/ghub-set-vars
- hack/glab-get-vars
- hack/glab-set-vars
- setup-local-dev-repos.sh
Plus some minor small other tweaks and fixes.
> Ensure GitLab secrets are updated when the exist already

- rhtap/env.template.sh
Set flag for TRUSTIFICATION to allow PRs to succeed - enables merge of SBOM Upload PR
> all PR to succeed if the TAS vars are not configured

- generated/source-repo/githubactions/.github/workflows/build-and-update-gitops.yml
- templates/source-repo/build-and-update-gitops.yml.njk
push events only on main, but still allow arbitrary run on workflow_dispatch
> Update github to only run on main for push

- rhtap/buildah-rhtap.sh
- rhtap/cosign-sign-attest.sh
or new IMAGE_REGISTRY_USER and IMAGE_REGISTRY_PASSWORD if configured
> use detection for registry

- ci-test.sh
- generated/gitops-template/githubactions/.github/workflows/gitops-promotion.yml
- generated/source-repo/githubactions/.github/workflows/build-and-update-gitops.yml
- hack/jenkins-run-pipeline
- hack/update-jenkins-library
- hack/wait-for-gitops-update.sh
- templates/gitops-template/gitops-promotion.yml.njk
- templates/source-repo/build-and-update-gitops.yml.njk
- e2e test for jenkins,gitlab,gitub
- updated to github versions (chore)
- add privileged to github gitops workflow to match build
> update to ci-test

- rhtap/show-sbom-rhdh.sh
- rhtap/summary.sh
Replaces tree command with a find and adds login for cosign
> fix cosign login and tree command

- .tekton/rhtap-task-runner-pull-request.yaml
- .tekton/rhtap-task-runner-push.yaml
- Dockerfile
- tools/rpm-manifests/rpms.in.yaml
- tools/rpm-manifests/rpms.lock.yaml
- tools/rpm-manifests/ubi.repo
This may be needed after we merge an MR that changes our Conforma policy (in an internal gitlab repo)
> runner image: meet productization requirements

- rhtap/acs-image-check.sh
Failure during roxctl-image-check currently does not cause the acs-image-check script to fail, resulting in a false negative.
> Fail acs-image-check task when image check fails

- rhtap/att-predicate-azure.sh
- rhtap/cosign-sign-attest.sh
Ref: https://issues.redhat.com/browse/EC-1160
> Generate initial SLSA Provenance for Azure

- rhtap/buildah-rhtap.sh
- rhtap/common.sh
- rhtap/cosign-sign-attest.sh
- rhtap/download-sbom-from-url-in-attestation.sh
- rhtap/show-sbom-rhdh.sh
- rhtap/summary.sh
- rhtap/verify-enterprise-contract.sh
This commit moves the logic of performing a login to a function in common.sh so other scripts can easily use it.
> Use consistent mechanism for registry login

- rhtap/env.template.sh
See also https://github.com/enterprise-contract/config/pull/173 which should be merged prior to this.
Ref: https://issues.redhat.com/browse/EC-1135
> Update default EC policy config in env template

- .github/workflows/checks.yml
- .yamllint
Add yaml lint check taken from konflux-ci/build-definitions
Checking generated workflow files, which are susceptible to errors
> Add yaml lint check

- hack/wait-for-gitops-update.sh
- rhtap/gather-deploy-images.sh
> Handle new placeholder image

- generated/gitops-template/azure/azure-pipelines.yml
- generated/source-repo/azure/azure-pipelines.yml
- templates/gitops-template/azure-pipelines.yml.njk
- templates/source-repo/azure-pipelines.yml.njk
Some of the changes were applied directly to the tssc-sample-templates repo instead of being done here first.
> Catch up on changes tssc-sample-templates

- rhtap/upload-sbom-to-trustification.sh
rh-pre-commit.version: 2.3.2
rh-pre-commit.check-secrets: ENABLED
> Update TPA API version to v2

- rhtap/upload-sbom-to-trustification.sh
In some cases, 'transfer-encoding: chunked' is causing curl to hang indefinetly when uploading an SBOM. There are two reasons one may want to use this chunked encoding.
First, if the length of the content being uploaded is unknown. This is not the case here since we have the full file before making the API call.
Second, if the file being uploaded is excessively large, the targeted server may require the data to be streamed via chunks. Although SBOMs can be quite large, we don't seem to be anywhere near it. (The limit on TPA is currently not documented.)
It is also important to call out that when using chunked encoding, "the content-length header must be omitted":
https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Headers/Transfer-Encoding#chunked
For these reasonse, this commit …
> Remove chunked encoding

- integration-tests/README.md
- integration-tests/config/rhads-config
- integration-tests/config/testplan.json
Add integration tests to run PR check.
> RHTAP-3363: Add integration tests to run tssc-test

- integration-tests/config/rhads-config
- integration-tests/config/testplan.json
In context of pr https://github.com/redhat-appstudio/rhtap-cli/pull/1029, removing quay installation specific data from test
> remove quay integration test data
